FROM ubuntu:19.04
LABEL maintainer="diodonfrost <diodon.frost@diodonfrost.me>"

RUN apt-get update && apt-get install -y \
    git \
    puppet \
    apt-transport-https \
    curl \
    init \
    openssh-server openssh-client wget \
 && rm -rf /var/lib/apt/lists/*

ENTRYPOINT ["/sbin/init"]
